### ISSUE TITLE
Not returning multiple issue keys

### ISSUE THREAD

**Issue by jonaskuiler** [bitflight-devops/github-action-jira-find-issue-keys#16]
I'm passing a string with multiple issue keys, but the output of the action always just returns one (the first).

This is my configuration
```
- uses: bitflight-devops/github-action-jira-find-issue-keys@v1.1.8
              id: issues
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}
                  string: ${{ github.event.release.body }}
                  from: "string"
                  projects: "XYZ"
```

Where `github.event.release.body` is equal to `XYZ-1 XYZ-2 XYZ-3`

It seems the regex [here](https://github.com/bitflight-devops/github-action-jira-find-issue-keys/blob/main/src/utils.ts#L32) isn't greedy.
